spring:
  cloud:
    config:
      server:
        git:
          uri: file:/Users/huotaihe/local/data/config_server2
          force-pull: true
    consul:
      host: localhost
      port: 8500
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always