spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
turbine:
  aggregator:
    cluster-config: hytrix-consul-consumer
  app-config: hytrix-consul-consumer
