server:
  port: 0
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        register: false
      host: localhost
      port: 8500
feign:
  hystrix:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"