spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        prefer-ip-address: true
        register: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 0


resilience4j:
  circuitbreaker:
    backends:
      hello:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        event-consumer-buffer-size: 10
  bulkhead:
    backends:
      hello:
        max-concurrent-call: 5
        max-wait-time: 5
      hello2:
        max-concurrent-call: 1
        max-wait-time: 5
feign:
  client:
    config:
      default:
        connection-timeout: 500
        read-timeout: 500
